export const GET_COURSEBYCATE_REQUEST = "GET_COURSEBYCATE_REQUEST";
export const GET_COURSEBYCATE_SUCCESS = "GET_COURSEBYCATE_SUCCESS";
export const GET_COURSEBYCATE_FAILURE = "GET_COURSEBYCATE_FAILURE";
