export const GET_COURSES_REQUEST = 'GET_COURSES_REQUEST';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_FAILURE = 'GET_COURSES_FAILURE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const COURSE_DETAIL = 'COURSE_DETAIL';
