export const GET_COURSEDETAIL_REQUEST = 'GET_COURSEDETAIL_REQUEST';
export const GET_COURSEDETAIL_SUCCESS = 'GET_COURSEDETAIL_SUCCESS';
export const GET_COURSEDETAIL_FAILURE = 'GET_COURSEDETAIL_FAILURE';
