import React, { useState } from "react";
import { AiOutlineFile, AiFillPlayCircle } from "react-icons/ai";
import { FaAngleDown, FaAngleUp } from "react-icons/fa";
import CourseContentList from "./CourseContentList";
function CourseContent() {
    const courseList = [
        {
            id: 1,
            title: "Course Orientation",
            iconOpen: <FaAngleDown />,
            iconClose: <FaAngleUp />,
            hours: Math.floor(Math.random() * 24),
            minute: Math.floor(Math.random() * 60),
            subCourse: [
                {
                    subId: 1,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 2,
                    icon: <AiOutlineFile />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 3,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 4,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 5,
                    icon: <AiOutlineFile />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 6,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 7,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
            ],
        },
        {
            id: 2,
            title: "Course Orientation",
            iconOpen: <FaAngleDown />,
            iconClose: <FaAngleUp />,
            hours: Math.floor(Math.random() * 24),
            minute: Math.floor(Math.random() * 60),
            subCourse: [
                {
                    subId: 1,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 2,
                    icon: <AiOutlineFile />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 3,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 4,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 5,
                    icon: <AiOutlineFile />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 6,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 7,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
            ],
        },
        {
            id: 3,
            title: "Course Orientation",
            iconOpen: <FaAngleDown />,
            iconClose: <FaAngleUp />,
            hours: Math.floor(Math.random() * 24),
            minute: Math.floor(Math.random() * 60),
            subCourse: [
                {
                    subId: 1,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 2,
                    icon: <AiOutlineFile />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 3,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 4,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 5,
                    icon: <AiOutlineFile />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 6,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 7,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
            ],
        },
        {
            id: 4,
            title: "Course Orientation",
            iconOpen: <FaAngleDown />,
            iconClose: <FaAngleUp />,
            hours: Math.floor(Math.random() * 24),
            minute: Math.floor(Math.random() * 60),
            subCourse: [
                {
                    subId: 1,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 2,
                    icon: <AiOutlineFile />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 3,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 4,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 5,
                    icon: <AiOutlineFile />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 6,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 7,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
            ],
        },
        {
            id: 5,
            title: "Course Orientation",
            iconOpen: <FaAngleDown />,
            iconClose: <FaAngleUp />,
            hours: Math.floor(Math.random() * 24),
            minute: Math.floor(Math.random() * 60),
            subCourse: [
                {
                    subId: 1,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 2,
                    icon: <AiOutlineFile />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 3,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 4,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 5,
                    icon: <AiOutlineFile />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 6,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 7,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
            ],
        },
        {
            id: 6,
            title: "Course Orientation",
            iconOpen: <FaAngleDown />,
            iconClose: <FaAngleUp />,
            hours: Math.floor(Math.random() * 24),
            minute: Math.floor(Math.random() * 60),
            subCourse: [
                {
                    subId: 1,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 2,
                    icon: <AiOutlineFile />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 3,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 4,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 5,
                    icon: <AiOutlineFile />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 6,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 7,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
            ],
        },
        {
            id: 7,
            title: "Course Orientation",
            iconOpen: <FaAngleDown />,
            iconClose: <FaAngleUp />,
            hours: Math.floor(Math.random() * 24),
            minute: Math.floor(Math.random() * 60),
            subCourse: [
                {
                    subId: 1,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 2,
                    icon: <AiOutlineFile />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 3,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 4,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 5,
                    icon: <AiOutlineFile />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 6,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 7,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
            ],
        },
        {
            id: 8,
            title: "Course Orientation",
            iconOpen: <FaAngleDown />,
            iconClose: <FaAngleUp />,
            hours: Math.floor(Math.random() * 24),
            minute: Math.floor(Math.random() * 60),
            subCourse: [
                {
                    subId: 1,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 2,
                    icon: <AiOutlineFile />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 3,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 4,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 5,
                    icon: <AiOutlineFile />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 6,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 7,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
            ],
        },
        {
            id: 9,
            title: "Course Orientation",
            iconOpen: <FaAngleDown />,
            iconClose: <FaAngleUp />,
            hours: Math.floor(Math.random() * 24),
            minute: Math.floor(Math.random() * 60),
            subCourse: [
                {
                    subId: 1,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 2,
                    icon: <AiOutlineFile />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 3,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 4,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 5,
                    icon: <AiOutlineFile />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 6,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 7,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
            ],
        },
        {
            id: 10,
            title: "Course Orientation",
            iconOpen: <FaAngleDown />,
            iconClose: <FaAngleUp />,
            hours: Math.floor(Math.random() * 24),
            minute: Math.floor(Math.random() * 60),
            subCourse: [
                {
                    subId: 1,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 2,
                    icon: <AiOutlineFile />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 3,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 4,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 5,
                    icon: <AiOutlineFile />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 6,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 7,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
            ],
        },
        {
            id: 11,
            title: "Course Orientation",
            iconOpen: <FaAngleDown />,
            iconClose: <FaAngleUp />,
            hours: Math.floor(Math.random() * 24),
            minute: Math.floor(Math.random() * 60),
            subCourse: [
                {
                    subId: 1,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 2,
                    icon: <AiOutlineFile />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 3,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 4,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 5,
                    icon: <AiOutlineFile />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 6,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
                {
                    subId: 7,
                    icon: <AiFillPlayCircle />,
                    subTitle: "Welcome to the course!",
                    textPreview: "Preview",
                    time: Math.floor(Math.random() * 60),
                },
            ],
        },
    ];
    return (
        <div className="course-content">
            <div className="course-content__container">
                <div className="course-content__body">
                    <h1 className="course-content__heading">Course Content</h1>
                    <div className="course-content__subheader">
                        <span>60 sections</span>
                        <span> • 614 lectures</span>
                        <span> • 63h 12m total length</span>
                    </div>
                    <div className="course-content-list">
                        {courseList.map((item) => {
                            return <CourseContentList item={item} key={item.id} />;
                        })}
                    </div>
                </div>
            </div>
        </div>
    );
}

export default CourseContent;
